function Hd = filter_function
%FILTER_FUNCTION Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 11-Aug-2026 10:45:47

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 100;  % Sampling Frequency

N     = 41;  % Order
Fpass = 1;   % Passband Frequency
Fstop = 5;   % Stopband Frequency
Wpass = 1;   % Passband Weight
Wstop = 1;   % Stopband Weight
dens  = 20;  % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
